name: tests
on: workflow_dispatch
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node v18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Run Jasmine + Karma unit tests
        run: |
          npm i
          ng test --browsers ChromeHeadless --watch false
      - name: Run Cypress e2e tests
        run: ng e2e --headless --watch false
